package com.joinmoathir.app;

import android.app.*;
import android.os.Bundle;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

public class MainActivity extends Activity {
  static final int BLUE=0xff446ff2, BG=0xfff6f8fc, TEXT=0xff172033, MUTED=0xff7b869b;
  final SupabaseClient api=new SupabaseClient();
  FrameLayout body; LinearLayout nav; String tab="home";

  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xffffffff);showStart();}
  void showStart(){ if(api.restore(this)) showApp(); else showAuth(false); }

  void showAuth(boolean signup){
    LinearLayout root=Ui.v(this); root.setBackgroundColor(BG); root.setPadding(Ui.dp(this,22),Ui.dp(this,36),Ui.dp(this,22),Ui.dp(this,24));
    Space top=new Space(this); root.addView(top,new LinearLayout.LayoutParams(1,0,1));
    TextView mark=Ui.t(this,"م",36,0xffffffff,true); mark.setGravity(Gravity.CENTER); mark.setBackground(Ui.round(BLUE,24));
    LinearLayout.LayoutParams mlp=new LinearLayout.LayoutParams(Ui.dp(this,76),Ui.dp(this,76)); mlp.gravity=Gravity.CENTER_HORIZONTAL; root.addView(mark,mlp);
    TextView brand=Ui.t(this,"مؤثر",31,TEXT,true); brand.setGravity(Gravity.CENTER); root.addView(brand,Ui.mw());
    TextView sub=Ui.t(this,"منصة صناع المحتوى في العراق",14,MUTED,false); sub.setGravity(Gravity.CENTER); root.addView(sub,Ui.mw());
    LinearLayout card=Ui.card(this); card.setPadding(Ui.dp(this,18),Ui.dp(this,18),Ui.dp(this,18),Ui.dp(this,18));
    TextView title=Ui.t(this,signup?"إنشاء حساب":"تسجيل الدخول",23,TEXT,true); title.setGravity(Gravity.RIGHT); card.addView(title,Ui.mw());
    EditText name=Ui.input(this,"الاسم"); if(signup) card.addView(name,Ui.field(this));
    EditText email=Ui.input(this,"الإيميل"); email.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS); card.addView(email,Ui.field(this));
    EditText pass=Ui.input(this,"كلمة السر"); pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD); card.addView(pass,Ui.field(this));
    TextView msg=Ui.t(this,"",12,0xffc63636,false); msg.setGravity(Gravity.RIGHT); card.addView(msg,Ui.mw());
    Button go=Ui.primary(this,signup?"إنشاء الحساب":"دخول"); card.addView(go,Ui.button(this));
    Button toggle=Ui.ghost(this,signup?"عندك حساب؟ سجل دخول":"ما عندك حساب؟ سجّل الآن"); card.addView(toggle,Ui.button(this));
    go.setOnClickListener(v->{String e=email.getText().toString().trim(),p=pass.getText().toString(); if(e.isEmpty()||p.length()<6){msg.setText("تأكد من الإيميل وكلمة السر");return;} go.setEnabled(false);go.setText("جارٍ..."); api.auth(this,signup,e,p,name.getText().toString().trim(),new SupabaseClient.Callback(){public void ok(JSONArray a){runOnUiThread(()->showApp());} public void fail(String s){runOnUiThread(()->{go.setEnabled(true);go.setText(signup?"إنشاء الحساب":"دخول");msg.setText(s);});}});});
    toggle.setOnClickListener(v->showAuth(!signup));
    LinearLayout.LayoutParams clp=Ui.mw(); clp.topMargin=Ui.dp(this,28); root.addView(card,clp);
    Space bottom=new Space(this); root.addView(bottom,new LinearLayout.LayoutParams(1,0,1)); setContentView(root);
  }

  void showApp(){
    LinearLayout root=Ui.v(this); root.setBackgroundColor(BG);
    LinearLayout head=Ui.h(this); head.setGravity(Gravity.CENTER_VERTICAL); head.setPadding(Ui.dp(this,18),0,Ui.dp(this,18),0); head.setBackgroundColor(0xffffffff);
    TextView brand=Ui.t(this,"مؤثر",23,TEXT,true); head.addView(brand,new LinearLayout.LayoutParams(0,Ui.dp(this,62),1));
    TextView nativeTag=Ui.t(this,"ANDROID NATIVE",10,BLUE,true); nativeTag.setGravity(Gravity.CENTER); nativeTag.setBackground(Ui.round(0xffeef3ff,99)); head.addView(nativeTag,new LinearLayout.LayoutParams(Ui.dp(this,112),Ui.dp(this,32)));
    root.addView(head,new LinearLayout.LayoutParams(-1,Ui.dp(this,62)));
    body=new FrameLayout(this); root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
    nav=Ui.h(this); nav.setBackgroundColor(0xffffffff); String[][] tabs={{"home","الرئيسية","⌂"},{"discover","اكتشف","⌕"},{"projects","الفرص","▣"},{"community","المجتمع","◉"},{"me","حسابي","●"}};
    for(String[] x:tabs){Button b=Ui.nav(this,x[2]+"\n"+x[1]); b.setTag(x[0]); b.setOnClickListener(v->switchTab((String)v.getTag())); nav.addView(b,new LinearLayout.LayoutParams(0,Ui.dp(this,70),1));}
    root.addView(nav,new LinearLayout.LayoutParams(-1,Ui.dp(this,70))); setContentView(root); switchTab("home");
  }

  void switchTab(String id){tab=id; for(int i=0;i<nav.getChildCount();i++){Button b=(Button)nav.getChildAt(i); boolean on=id.equals(b.getTag());b.setTextColor(on?BLUE:MUTED);b.setBackgroundColor(on?0xffeef3ff:0xffffffff);} if(id.equals("home")) home(); else if(id.equals("discover")) discover(); else if(id.equals("projects")) projects(); else if(id.equals("community")) community(); else account();}
  void loading(){body.removeAllViews(); ProgressBar p=new ProgressBar(this); FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48),Gravity.CENTER);body.addView(p,lp);}
  ScrollView page(){ScrollView s=new ScrollView(this); LinearLayout box=Ui.v(this);box.setPadding(Ui.dp(this,14),Ui.dp(this,14),Ui.dp(this,14),Ui.dp(this,28));s.addView(box);s.setTag(box);return s;}
  LinearLayout box(ScrollView s){return (LinearLayout)s.getTag();}
  void putPage(ScrollView s){body.removeAllViews();body.addView(s,new FrameLayout.LayoutParams(-1,-1));}
  void fetch(String path, SupabaseClient.Callback cb){loading();api.get(path,cb);}

  void home(){fetch("/rest/v1/profiles_public?select=id,display_name,city,primary_category,verified,instagram_followers,tiktok_followers&account_type=eq.creator&onboarded=eq.true&order=created_at.desc&limit=12",new SupabaseClient.Callback(){public void ok(JSONArray rows){runOnUiThread(()->{ScrollView s=page();LinearLayout b=box(s);LinearLayout hero=Ui.v(MainActivity.this);hero.setPadding(Ui.dp(MainActivity.this,20),Ui.dp(MainActivity.this,18),Ui.dp(MainActivity.this,20),Ui.dp(MainActivity.this,18));hero.setBackground(Ui.round(BLUE,24));TextView h=Ui.t(MainActivity.this,"أهلاً بك في مؤثر",25,0xffffffff,true);h.setGravity(Gravity.RIGHT);hero.addView(h,Ui.mw());TextView q=Ui.t(MainActivity.this,"اكتشف صناع محتوى وفرص تعاون حقيقية",13,0xffdce5ff,false);q.setGravity(Gravity.RIGHT);hero.addView(q,Ui.mw());b.addView(hero,Ui.cardLp(MainActivity.this));section(b,"صناع محتوى مقترحون");creators(b,rows);putPage(s);});}public void fail(String e){error(e);}});}

  void discover(){fetch("/rest/v1/profiles_public?select=id,display_name,city,primary_category,verified,instagram_followers,tiktok_followers,youtube_followers,snapchat_followers&account_type=eq.creator&onboarded=eq.true&order=created_at.desc&limit=100",new SupabaseClient.Callback(){public void ok(JSONArray rows){runOnUiThread(()->{ScrollView s=page();LinearLayout b=box(s);EditText search=Ui.input(MainActivity.this,"ابحث عن مؤثر...");b.addView(search,Ui.field(MainActivity.this));LinearLayout list=Ui.v(MainActivity.this);b.addView(list,Ui.mw());Runnable draw=()->{list.removeAllViews();String k=search.getText().toString().trim().toLowerCase(Locale.ROOT);for(int i=0;i<rows.length();i++){JSONObject x=rows.optJSONObject(i);String hay=(x.optString("display_name")+" "+x.optString("city")+" "+x.optString("primary_category")).toLowerCase(Locale.ROOT);if(k.isEmpty()||hay.contains(k)) list.addView(creatorCard(x),Ui.cardLp(MainActivity.this));}};search.addTextChangedListener(new Ui.Watcher(draw));draw.run();putPage(s);});}public void fail(String e){error(e);}});}

  void projects(){fetch("/rest/v1/projects?select=id,title,description,status,slots_needed,city,created_at&order=created_at.desc&limit=50",new SupabaseClient.Callback(){public void ok(JSONArray rows){runOnUiThread(()->{ScrollView s=page();LinearLayout b=box(s);LinearLayout line=Ui.h(MainActivity.this);TextView t=Ui.t(MainActivity.this,"فرص التعاون",21,TEXT,true);t.setGravity(Gravity.RIGHT);line.addView(t,new LinearLayout.LayoutParams(0,Ui.dp(MainActivity.this,48),1));Button add=Ui.primary(MainActivity.this,"+ فرصة");line.addView(add,new LinearLayout.LayoutParams(Ui.dp(MainActivity.this,110),Ui.dp(MainActivity.this,46)));b.addView(line,Ui.mw());add.setOnClickListener(v->projectDialog());for(int i=0;i<rows.length();i++)b.addView(projectCard(rows.optJSONObject(i)),Ui.cardLp(MainActivity.this));if(rows.length()==0)b.addView(Ui.empty(MainActivity.this,"ماكو فرص حالياً"),Ui.mw());putPage(s);});}public void fail(String e){error(e);}});}

  void community(){fetch("/rest/v1/posts_public?select=id,body,likes_count,replies_count,created_at&parent_id=is.null&order=created_at.desc&limit=50",new SupabaseClient.Callback(){public void ok(JSONArray rows){runOnUiThread(()->{ScrollView s=page();LinearLayout b=box(s);LinearLayout composer=Ui.card(MainActivity.this);composer.setPadding(Ui.dp(MainActivity.this,14),Ui.dp(MainActivity.this,14),Ui.dp(MainActivity.this,14),Ui.dp(MainActivity.this,14));EditText post=Ui.input(MainActivity.this,"بشنو تفكر؟");post.setSingleLine(false);post.setMinLines(3);composer.addView(post,Ui.area(MainActivity.this));Button send=Ui.primary(MainActivity.this,"نشر");composer.addView(send,Ui.button(MainActivity.this));send.setOnClickListener(v->post(post.getText().toString()));b.addView(composer,Ui.cardLp(MainActivity.this));for(int i=0;i<rows.length();i++){JSONObject x=rows.optJSONObject(i);LinearLayout c=Ui.card(MainActivity.this);c.setPadding(Ui.dp(MainActivity.this,15),Ui.dp(MainActivity.this,15),Ui.dp(MainActivity.this,15),Ui.dp(MainActivity.this,15));TextView bt=Ui.t(MainActivity.this,x.optString("body"),14,0xff344057,false);bt.setGravity(Gravity.RIGHT);c.addView(bt,Ui.mw());TextView m=Ui.t(MainActivity.this,"♡ "+x.optInt("likes_count")+"   ◌ "+x.optInt("replies_count"),11,MUTED,false);m.setGravity(Gravity.RIGHT);c.addView(m,Ui.mw());b.addView(c,Ui.cardLp(MainActivity.this));}putPage(s);});}public void fail(String e){error(e);}});}

  void account(){fetch("/rest/v1/profiles?id=eq."+api.userId+"&select=display_name,business_name,account_type,city,bio&limit=1",new SupabaseClient.Callback(){public void ok(JSONArray a){runOnUiThread(()->{JSONObject p=a.optJSONObject(0);if(p==null)p=new JSONObject();ScrollView s=page();LinearLayout b=box(s);LinearLayout c=Ui.card(MainActivity.this);c.setGravity(Gravity.CENTER_HORIZONTAL);c.setPadding(Ui.dp(MainActivity.this,20),Ui.dp(MainActivity.this,22),Ui.dp(MainActivity.this,20),Ui.dp(MainActivity.this,22));TextView av=Ui.t(MainActivity.this,initial(p.optString("display_name","م")),32,BLUE,true);av.setGravity(Gravity.CENTER);av.setBackground(Ui.round(0xffeef3ff,24));c.addView(av,new LinearLayout.LayoutParams(Ui.dp(MainActivity.this,86),Ui.dp(MainActivity.this,86)));TextView n=Ui.t(MainActivity.this,p.optString("display_name",p.optString("business_name","مستخدم")),22,TEXT,true);n.setGravity(Gravity.CENTER);c.addView(n,Ui.mw());TextView mail=Ui.t(MainActivity.this,api.email,12,MUTED,false);mail.setGravity(Gravity.CENTER);c.addView(mail,Ui.mw());Button out=Ui.ghost(MainActivity.this,"تسجيل الخروج");c.addView(out,Ui.button(MainActivity.this));out.setOnClickListener(v->{api.logout(MainActivity.this);showAuth(false);});b.addView(c,Ui.cardLp(MainActivity.this));putPage(s);});}public void fail(String e){error(e);}});}

  void creators(LinearLayout b,JSONArray a){for(int i=0;i<a.length();i++)b.addView(creatorCard(a.optJSONObject(i)),Ui.cardLp(this));if(a.length()==0)b.addView(Ui.empty(this,"ماكو صناع محتوى حالياً"),Ui.mw());}
  View creatorCard(JSONObject x){LinearLayout c=Ui.card(this);c.setPadding(Ui.dp(this,14),Ui.dp(this,14),Ui.dp(this,14),Ui.dp(this,14));LinearLayout r=Ui.h(this);TextView av=Ui.t(this,initial(x.optString("display_name")),22,BLUE,true);av.setGravity(Gravity.CENTER);av.setBackground(Ui.round(0xffeef3ff,20));r.addView(av,new LinearLayout.LayoutParams(Ui.dp(this,58),Ui.dp(this,58)));LinearLayout info=Ui.v(this);info.setPadding(Ui.dp(this,12),0,0,0);TextView n=Ui.t(this,x.optString("display_name","صانع محتوى")+(x.optBoolean("verified")?" ✓":""),16,TEXT,true);n.setGravity(Gravity.RIGHT);info.addView(n,Ui.mw());TextView m=Ui.t(this,meta(x.optString("primary_category"),x.optString("city")),12,MUTED,false);m.setGravity(Gravity.RIGHT);info.addView(m,Ui.mw());long f=x.optLong("instagram_followers")+x.optLong("tiktok_followers")+x.optLong("youtube_followers")+x.optLong("snapchat_followers");if(f>0){TextView ff=Ui.t(this,followers(f)+" متابع",11,BLUE,true);ff.setGravity(Gravity.RIGHT);info.addView(ff,Ui.mw());}r.addView(info,new LinearLayout.LayoutParams(0,-2,1));c.addView(r,Ui.mw());c.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(x.optString("display_name","مؤثر")).setMessage(meta(x.optString("primary_category"),x.optString("city"))).setPositiveButton("حسناً",null).show());return c;}
  View projectCard(JSONObject x){LinearLayout c=Ui.card(this);c.setPadding(Ui.dp(this,15),Ui.dp(this,15),Ui.dp(this,15),Ui.dp(this,15));TextView t=Ui.t(this,x.optString("title","فرصة تعاون"),16,TEXT,true);t.setGravity(Gravity.RIGHT);c.addView(t,Ui.mw());TextView d=Ui.t(this,x.optString("description"),13,0xff344057,false);d.setGravity(Gravity.RIGHT);d.setLineSpacing(0,1.2f);c.addView(d,Ui.mw());TextView m=Ui.t(this,(x.optInt("slots_needed",1))+" مطلوب • "+x.optString("city","العراق"),11,MUTED,false);m.setGravity(Gravity.RIGHT);c.addView(m,Ui.mw());return c;}
  void projectDialog(){LinearLayout b=Ui.v(this);b.setPadding(Ui.dp(this,18),0,Ui.dp(this,18),0);EditText title=Ui.input(this,"عنوان الفرصة");EditText desc=Ui.input(this,"تفاصيل التعاون المطلوب");desc.setSingleLine(false);desc.setMinLines(4);b.addView(title,Ui.field(this));b.addView(desc,Ui.area(this));new AlertDialog.Builder(this).setTitle("نشر فرصة").setView(b).setNegativeButton("إلغاء",null).setPositiveButton("نشر",(d,w)->{String t=title.getText().toString().trim(),q=desc.getText().toString().trim();if(t.length()<3||q.length()<10){toast("اكتب تفاصيل أوضح");return;}JSONObject o=new JSONObject();try{o.put("owner_id",api.userId);o.put("title",t);o.put("description",q);o.put("category","فرصة تعاون");o.put("budget",0);o.put("city","—");o.put("gender","الكل");o.put("age_range","الكل");o.put("content_type","business");o.put("slots_needed",1);o.put("max_price",JSONObject.NULL);o.put("expires_at",SupabaseClient.afterDays(7));}catch(Exception ignored){}api.post("/rest/v1/projects",o.toString(),"return=minimal",new SupabaseClient.Callback(){public void ok(JSONArray a){runOnUiThread(()->{toast("تم نشر الفرصة");projects();});}public void fail(String e){runOnUiThread(()->toast(e));}});}).show();}
  void post(String text){text=text.trim();if(text.isEmpty())return;JSONObject o=new JSONObject();try{o.put("author_id",api.userId);o.put("body",text);o.put("parent_id",JSONObject.NULL);o.put("is_anonymous",false);o.put("is_opportunity",false);}catch(Exception ignored){}api.post("/rest/v1/posts",o.toString(),"return=minimal",new SupabaseClient.Callback(){public void ok(JSONArray a){runOnUiThread(()->{toast("تم النشر");community();});}public void fail(String e){runOnUiThread(()->toast(e));}});}
  void error(String e){runOnUiThread(()->{body.removeAllViews();LinearLayout b=Ui.v(this);b.setGravity(Gravity.CENTER);TextView t=Ui.t(this,e,14,0xffc63636,false);t.setGravity(Gravity.CENTER);b.addView(t,Ui.mw());Button r=Ui.primary(this,"إعادة المحاولة");LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(Ui.dp(this,180),Ui.dp(this,48));lp.gravity=Gravity.CENTER_HORIZONTAL;lp.topMargin=Ui.dp(this,14);b.addView(r,lp);r.setOnClickListener(v->switchTab(tab));body.addView(b,new FrameLayout.LayoutParams(-1,-1));});}
  void section(LinearLayout b,String s){TextView t=Ui.t(this,s,20,TEXT,true);t.setGravity(Gravity.RIGHT);LinearLayout.LayoutParams lp=Ui.mw();lp.topMargin=Ui.dp(this,8);lp.bottomMargin=Ui.dp(this,10);b.addView(t,lp);}
  String initial(String s){s=s==null?"":s.trim();return s.isEmpty()?"م":s.substring(0,1);} String meta(String a,String b){a=a==null?"":a.trim();b=b==null?"":b.trim();if(a.isEmpty())return b.isEmpty()?"مؤثر":b;if(b.isEmpty())return a;return a+" • "+b;} String followers(long n){if(n>=1000000)return String.format(Locale.US,"%.1fم",n/1000000.0);if(n>=1000)return String.format(Locale.US,n>=10000?"%.0fألف":"%.1fألف",n/1000.0);return String.valueOf(n);} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
